### ISSUE TITLE
Provide Accessibility

### ISSUE THREAD

**Issue by dovematrix** [radiantmediaplayer/rmp-free-edition-quick-start#1]
The WAVE toolbar for Chrome reports two errors: missing alternative text on the poster image, and a missing form label.

**Comment by radiantmediaplayer** [comment]
@dovematrix thanks for your feedback.
I have added those 2 items for review for our next patch release.

**Comment by radiantmediaplayer** [comment]
Fixed with 3.8.2. A list of updated accessibility features for Radiant Media Player can be found [here](https://www.radiantmediaplayer.com/docs/3.0/accessibility-features.html).
